services:
  home:
    build: .
    volumes:
      - ./data:/data
    ports:
      - 80:8080
    secrets:
      - secret-properties
    restart: on-failure
    image: home:1
    container_name: home
    networks:
      - nu

secrets:
  secret-properties:
    file: ./secret.properties

networks:
  nu:
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
       - subnet: 172.16.238.0/24
         gateway: 172.16.238.1
       - subnet: 2001:3984:3989::/64
         gateway: 2001:3984:3989::1
