apiVersion: v1
kind: Service
metadata:
  name: homealone
spec:
  selector:
    name: homealone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homealone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: homealone
  template:
    metadata:
      labels:
        name: homealone
        app: homealone
    spec:
      containers:
        - name: homealone
          image: pochemuto/homealone:v3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: testing
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: homealone-secrets
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homealone-secrets
                  key: mail_password
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: homealone-secrets
                  key: bot_token
            - name: BOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: homealone-secrets
                  key: bot_username
            - name: MARAFON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homealone-secrets
                  key: marafon_password

          ports:
            - containerPort: 8081

          readinessProbe:
            tcpSocket:
              port: 8081

          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: homealone-config
            items:
              - key: testing
                path: application-testing.yml
        - name: homealone-secrets
          secret:
            secretName: homealone-secrets
        - name: mongo
          secret:
            secretName: mongo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homealone
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - homealone.pochemuto.com
      secretName: homealone-letsencrypt-prod
  rules:
    - host: homealone.pochemuto.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: homealone
              servicePort: 80
