apiVersion: v1
kind: Service
metadata:
  name: homealone
spec:
  selector:
    name: homealone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homealone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: homealone
  template:
    metadata:
      labels:
        name: homealone
        app: homealone
    spec:
      containers:
        - name: homealone
          image: cr.yandex/crp4g65pbp8qf4mtcos7/homealone
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: testing
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: password
          ports:
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: homealone
            items:
              - key: testing
                path: application-testing.yaml
        - name: mongo
          secret:
            secretName: mongo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homealone
data:
  testing: |
    spring:
      data:
        mongodb:
          database: main
          host: mongo
          port: 27018
          replica-set-name: rs01

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homealone
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - homealone.pochemuto.com
      secretName: homealone-letsencrypt-prod
  rules:
    - host: homealone.pochemuto.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              serviceName: homealone
              servicePort: 80
