application:
    scheduling:
        enabled: false

telegrambots:
    enabled: false

spring:
    boot:
        admin:
            client:
                enabled: false

    data:
        mongodb:
            host: ''
