name: Deploy-testing

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            GITHUB_SHA
          tags: |
            pochemuto/homealone:${{ github.sha }}
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Yandex Cloud CLI
      run: wget https://storage.yandexcloud.net/yandexcloud-yc/install.sh && chmod +x install.sh && ./install.sh -i /home/runner/yandex-cloud

    - name: Setup account
      run: echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY }}' > key.json && /home/runner/yandex-cloud/bin/yc config set service-account-key key.json

    - name: Set context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: '${{ secrets.KUBE_CONFIG }}'
      id: setcontext

    - name: Apply to Kubernetes [testing]
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: kube/testing.yaml
        images: 'pochemuto/homealone:${{ github.sha }}'
