name: Build project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          build-args: |
            VERSION=${{ github.sha }}
          tags: |
            pochemuto/homealone:${{ github.sha }}
